export const ErrorCodes = {
  // generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // auth
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',

  // users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  ROLE_NOT_ALLOWED: 'ROLE_NOT_ALLOWED',

  // documents
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_FILE_MISSING: 'DOCUMENT_FILE_MISSING',
  DOCUMENT_FILE_TOO_LARGE: 'DOCUMENT_FILE_TOO_LARGE',
  DOCUMENT_MIME_NOT_ALLOWED: 'DOCUMENT_MIME_NOT_ALLOWED',
  DOCUMENT_MIME_MISMATCH: 'DOCUMENT_MIME_MISMATCH',

  // delegations
  DELEGATION_REQUEST_NOT_FOUND: 'DELEGATION_REQUEST_NOT_FOUND',
  DELEGATION_REQUEST_EXPIRED: 'DELEGATION_REQUEST_EXPIRED',
  DELEGATION_REQUEST_NOT_PENDING: 'DELEGATION_REQUEST_NOT_PENDING',
  DELEGATION_REQUEST_FORBIDDEN: 'DELEGATION_REQUEST_FORBIDDEN',
  DELEGATION_TARGET_FISCAL_MISMATCH: 'DELEGATION_TARGET_FISCAL_MISMATCH',
  DELEGATION_TARGET_ALREADY_REGISTERED: 'DELEGATION_TARGET_ALREADY_REGISTERED',
  DELEGATION_SELF_REQUEST: 'DELEGATION_SELF_REQUEST',
  DELEGATION_DUPLICATE_ACTIVE: 'DELEGATION_DUPLICATE_ACTIVE',
  DELEGATION_NOT_FOUND: 'DELEGATION_NOT_FOUND',
  DELEGATION_NOT_ACTIVE: 'DELEGATION_NOT_ACTIVE',
  DELEGATION_SUB_NOT_AUTHORIZED: 'DELEGATION_SUB_NOT_AUTHORIZED',
  DELEGATION_SUB_PARENT_INACTIVE: 'DELEGATION_SUB_PARENT_INACTIVE',
  DELEGATION_REVOKE_FORBIDDEN: 'DELEGATION_REVOKE_FORBIDDEN',
  ACTING_AS_NOT_ALLOWED: 'ACTING_AS_NOT_ALLOWED',

  // otp
  OTP_NOT_REQUESTED: 'OTP_NOT_REQUESTED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

const STATUS_BY_CODE: Record<ErrorCode, number> = {
  VALIDATION_FAILED: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,

  EMAIL_ALREADY_EXISTS: 409,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_LOCKED: 423,
  EMAIL_NOT_VERIFIED: 403,
  REFRESH_TOKEN_INVALID: 401,
  REFRESH_TOKEN_EXPIRED: 401,
  REFRESH_TOKEN_REVOKED: 401,

  USER_NOT_FOUND: 404,
  PROFILE_NOT_FOUND: 404,
  ROLE_NOT_ALLOWED: 403,

  DOCUMENT_NOT_FOUND: 404,
  DOCUMENT_FILE_MISSING: 400,
  DOCUMENT_FILE_TOO_LARGE: 413,
  DOCUMENT_MIME_NOT_ALLOWED: 415,
  DOCUMENT_MIME_MISMATCH: 415,

  DELEGATION_REQUEST_NOT_FOUND: 404,
  DELEGATION_REQUEST_EXPIRED: 410,
  DELEGATION_REQUEST_NOT_PENDING: 409,
  DELEGATION_REQUEST_FORBIDDEN: 403,
  DELEGATION_TARGET_FISCAL_MISMATCH: 403,
  DELEGATION_TARGET_ALREADY_REGISTERED: 409,
  DELEGATION_SELF_REQUEST: 400,
  DELEGATION_DUPLICATE_ACTIVE: 409,
  DELEGATION_NOT_FOUND: 404,
  DELEGATION_NOT_ACTIVE: 409,
  DELEGATION_SUB_NOT_AUTHORIZED: 403,
  DELEGATION_SUB_PARENT_INACTIVE: 409,
  DELEGATION_REVOKE_FORBIDDEN: 403,
  ACTING_AS_NOT_ALLOWED: 403,

  OTP_NOT_REQUESTED: 409,
  OTP_INVALID: 401,
  OTP_EXPIRED: 410,
  OTP_TOO_MANY_ATTEMPTS: 429,
};

export function statusForCode(code: ErrorCode): number {
  return STATUS_BY_CODE[code] ?? 500;
}

export class CodedException extends Error {
  readonly code: ErrorCode;
  readonly status: number;
  readonly details?: Record<string, unknown>;

  constructor(code: ErrorCode, details?: Record<string, unknown>) {
    super(code);
    this.code = code;
    this.status = statusForCode(code);
    this.details = details;
  }
}
